### ISSUE TITLE
Some problem with streamer class

### ISSUE THREAD

**Issue by 2pysarthak** [dilawar/moose-core#3]
[Issue.zip](https://github.com/dilawar/moose-core/files/274523/Issue.zip)

I have added the folder with the testing code and all the required files.

**Comment by dilawar** [comment]
Fixed by commit  806f6a1. The wildcard patter is wrong in python script. you were trying to add 0 tables to streamer. This has been fixed in c++ core: user gets a notification.

```
tables  = moose.wildcardFind( '/model/#[TYPE=Table]')
assert len(tables) > 0, "Zero table"
```
is a good way to add table.  I am checking the output of streamer class once simulation is over. For now, issue is closed. If something else pops up, reopen the issue.
